# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Fundamentos de Programación en Python
author: "" # Félix Miguel Trespaderne / Rogelio Mazaeda Echevarría
logo: logo.png
copyright: "Félix Miguel Trespaderne / Rogelio Mazaeda Echevarría"

exclude_patterns            : [_build, Thumbs.db, .DS_Store, "**.md", "**.ipynb_checkpoints"]
# Auto-exclude files not in the toc
only_build_toc_files        : true

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: force  # cache
 

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

# Information about where the book exists on the web
repository:
  url: https://github.com/TRESPADERNE/fund_prog_python  # Online location of your book
  branch: master  # Which branch of the repository should be used when creating links (optional)

#######################################################################################
# Parse and render settings
parse:
  myst_extended_syntax      : true  # enable MyST extended syntax support (see documents for details)


# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository

html:
  use_repository_button     : true
  use_issues_button         : false
  use_edit_page_button      : false
  extra_navbar              : false
  extra_footer              : |
    <div>
    <a href="https://creativecommons.org/licenses/by-nc-sa/4.0/"><img src="https://licensebuttons.net/l/by-nc-sa/3.0/88x31.png"></a>
        All content on this site (unless otherwise specified) is licensed under the <a href="https://creativecommons.org/licenses/by-nc-sa/4.0/">CC BY-NC-SA 4.0 license</a>
    </div>



sphinx:
   config:
      html_theme_options : {"use_download_button": False, "repository_url": "https://github.com/TRESPADERNE/fund_prog_python", "use_repository_button": True, 
                            "extra_footer": <div> <a href="https://creativecommons.org/licenses/by-nc-sa/4.0/"><img src="https://licensebuttons.net/l/by-nc-sa/3.0/88x31.png"></a>All content on this site (unless otherwise specified) is licensed under the <a href="https://creativecommons.org/licenses/by-nc-sa/4.0/">CC BY-NC-SA 4.0 license</a></div>,}