# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Fundamentos de Programación en Python
author: Félix Miguel Trespaderne / Rogelio Mazaeda Echevarría
logo: logo.png

exclude_patterns            : [_build, Thumbs.db, .DS_Store, "**.ipynb_checkpoints"]
# Auto-exclude files not in the toc
only_build_toc_files        : true

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: force  # cache
 

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

# Information about where the book exists on the web
repository:
  url: https://github.com/TRESPADERNE/fund_prog_python  # Online location of your book
# path_to_book: docs  # Optional path to your book, relative to the repository root
  branch: master  # Which branch of the repository should be used when creating links (optional)

#######################################################################################
# Parse and render settings
parse:
  myst_extended_syntax      : true  # enable MyST extended syntax support (see documents for details)


# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button         : true
  use_repository_button     : true
  extra_footer              : |
    <div>
    <a href="http://creativecommons.org/licenses/by-nc-sa/4.0/"><img class="license" alt="Creative Commons License" src="https://i.creativecommons.org/l/by-nc-sa/4.0/80x15.png" /></a> This book is licensed under a <a href="https://creativecommons.org/licenses/by-nc-sa/4.0/">Creative Commons BY-NC-SA 4.0 License</a>. The code is licensed under a <a href="https://choosealicense.com/licenses/gpl-3.0/#">GNU General Public License v3.0</a>.
    </div>

# sphinx:
#  extra_extensions: ['sphinx_rtd_theme']
#  config                    :  
#      html_theme : "sphinx_rtd_theme"